from crhelper import log_helper as log_helper
from typing import Any

logger: Any
SUCCESS: str
FAILED: str

class CfnResource:
    Status: str = ...
    Reason: str = ...
    PhysicalResourceId: str = ...
    StackId: str = ...
    RequestId: str = ...
    LogicalResourceId: str = ...
    Data: Any = ...
    NoEcho: bool = ...
    def __init__(self, json_logging: bool = ..., log_level: str = ..., boto_level: str = ..., polling_interval: int = ..., sleep_on_delete: int = ...) -> None: ...
    def __call__(self, event: Any, context: Any) -> None: ...
    def generate_physical_id(self, event: Any): ...
    def create(self, func: Any): ...
    def update(self, func: Any): ...
    def delete(self, func: Any): ...
    def poll_create(self, func: Any): ...
    def poll_update(self, func: Any): ...
    def poll_delete(self, func: Any): ...
    def init_failure(self, error: Any) -> None: ...
